POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "",
    "role": "tank",
    "avatar": {
        "accessory":"shades",
        "body":"chest",
        "clothing":"tankTop",
        "clothingColor":"black",
        "eyebrows":"angry",
        "eyes":"wink",
        "facialHair":"mediumBeard",
        "graphic":"vue",
        "hair":"short",
        "hairColor":"black",
        "hat":"none",
        "hatColor":"green",
        "lashes":"true",
        "lipColor":"purple",
        "mask":"true",
        "mouth":"open",
        "skinTone":"brown"
    }
}

###


POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "hellurei",
    "role": "",
    "avatar": {
        "accessory":"shades",
        "body":"chest",
        "clothing":"tankTop",
        "clothingColor":"black",
        "eyebrows":"angry",
        "eyes":"wink",
        "facialHair":"mediumBeard",
        "graphic":"vue",
        "hair":"short",
        "hairColor":"black",
        "hat":"none",
        "hatColor":"green",
        "lashes":"true",
        "lipColor":"purple",
        "mask":"true",
        "mouth":"open",
        "skinTone":"brown"
    }
}


###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "hellurei",
    "role": "tank",
}